<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::get('/bebas', function () {
    return response()->json([
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'armuji'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'budispeed'],
        ['name' => 'chef arnold'],
        ['name' => 'chef arnold'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
        ['name' => 'melvin tenggara'],
    ]);
});
